#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr 

sudo hwclock --localtime --hctosys

bspc monitor -d 喇     󰡉 󰎅 󰭺 X

bash ~/.config/polybar/docky/launch.sh

bspc rule -a Zathura state=tiled
bspc rule -a ranger state=floating
bspc rule -a Etterna state=floating

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme alternate
bspc config active_border_color F00
